[package]
name = "bowling-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "game"
path = "src/game.rs"

[[test]]
name = "game_tests"
path = "tests/game_test.rs"


[dependencies]
